var ProfileData = (function () {

    let user_data=[
        {id:1,name:"Entrepreneur"},
        {id:2,name:"Technocrat"},
        {id:3,name:"Investor"},
        {id:4,name:"Company"},
        {id:5,name:"Management Person"}
      ];

      let domain_data = [
        { id: 1, name: "Accommodation" },
        { id: 2, name: "Accommodation and Food Services" },
        { id: 3, name: "Administrative and Support Services" },
        { id: 4, name: "Administrative and Support and Waste Management and Remediation Services" },
        { id: 5, name: "Agriculture, Forestry, Fishing and Hunting" },
        { id: 6, name: "Air Transportation" },
        { id: 7, name: "Ambulatory Health Care Services" },
        { id: 8, name: "Amusement, Gambling, and Recreation Industries" },
        { id: 9, name: "Animal Production" },
        { id: 10, name: "Apparel Manufacturing" },
        { id: 11, name: "Arts, Entertainment, and Recreation" },
        { id: 12, name: "Beverage and Tobacco Product Manufacturing" },
        { id: 13, name: "Broadcasting (except Internet)" },
        { id: 14, name: "Building Material and Garden Equipment and Supplies Dealers" },
        { id: 15, name: "Chemical Manufacturing" },
        { id: 16, name: "Clothing and Clothing Accessories Stores" },
        { id: 17, name: "Computer and Electronic Product Manufacturing" },
        { id: 18, name: "Construction" },
        { id: 19, name: "Construction of Buildings" },
        { id: 20, name: "Couriers and Messengers" },
        { id: 21, name: "Credit Intermediation and Related Activities" },
        { id: 22, name: "Crop Production" },
        { id: 23, name: "Data Processing, Hosting, and Related Services" },
        { id: 24, name: "Education and Health Services" },
        { id: 25, name: "Educational Services" },
        { id: 26, name: "Electrical Equipment, Appliance, and Component Manufacturing" },
        { id: 27, name: "Electronics and Appliance Stores" },
        { id: 28, name: "Fabricated Metal Product Manufacturing" },
        { id: 29, name: "Finance and Insurance" },
        { id: 30, name: "Financial Activities" },
        { id: 31, name: "Fishing, Hunting and Trapping" },
        { id: 32, name: "Food Manufacturing" },
        { id: 33, name: "Food Services and Drinking Places" },
        { id: 34, name: "Food and Beverage Stores" },
        { id: 35, name: "Forestry and Logging" },
        { id: 36, name: "Funds, Trusts, and Other Financial Vehicles" },
        { id: 37, name: "Furniture and Home Furnishings Stores" },
        { id: 38, name: "Furniture and Related Product Manufacturing" },
        { id: 39, name: "Gasoline Stations" },
        { id: 40, name: "General Merchandise Stores" },
        { id: 41, name: "Goods-Producing Industries" },
        { id: 42, name: "Health Care and Social Assistance" },
        { id: 43, name: "Health and Personal Care Stores" },
        { id: 44, name: "Heavy and Civil Engineering Construction" },
        { id: 45, name: "Hospitals" },
        { id: 46, name: "Information" },
        { id: 47, name: "Insurance Carriers and Related Activities" },
        { id: 48, name: "Internet Publishing and Broadcasting" },
        { id: 49, name: "Leather and Allied Product Manufacturing" },
        { id: 50, name: "Leisure and Hospitality" },
        { id: 51, name: "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)" },
        { id: 52, name: "Machinery Manufacturing" },
        { id: 53, name: "Management of Companies and Enterprises" },
        { id: 54, name: "Manufacturing" },
        { id: 55, name: "Merchant Wholesalers, Durable Goods" },
        { id: 56, name: "Merchant Wholesalers, Nondurable Goods" },
        { id: 57, name: "Mining (except Oil and Gas)" },
        { id: 58, name: "Mining, Quarrying, and Oil and Gas Extraction" },
        { id: 59, name: "Miscellaneous Manufacturing" },
        { id: 60, name: "Miscellaneous Store Retailers" },
        { id: 61, name: "Monetary Authorities - Central Bank" },
        { id: 62, name: "Motion Picture and Sound Recording Industries" },
        { id: 63, name: "Motor Vehicle and Parts Dealers" },
        { id: 64, name: "Museums, Historical Sites, and Similar Institutions" },
        { id: 65, name: "Natural Resources and Mining" },
        { id: 66, name: "Nonmetallic Mineral Product Manufacturing" },
        { id: 67, name: "Nonstore Retailers" },
        { id: 68, name: "Nursing and Residential Care Facilities" },
        { id: 69, name: "Oil and Gas Extraction" },
        { id: 70, name: "Other Information Services" },
        { id: 71, name: "Other Services (except Public Administration)" },
        { id: 72, name: "Paper Manufacturing" },
        { id: 73, name: "Performing Arts, Spectator Sports, and Related Industries" },
        { id: 74, name: "Personal and Laundry Services" },
        { id: 75, name: "Petroleum and Coal Products Manufacturing" },
        { id: 76, name: "Pipeline Transportation" },
        { id: 77, name: "Plastics and Rubber Products Manufacturing" },
        { id: 78, name: "Postal Service" },
        { id: 79, name: "Primary Metal Manufacturing" },
        { id: 80, name: "Printing and Related Support Activities" },
        { id: 81, name: "Private Households" },
        { id: 82, name: "Professional and Business Services" },
        { id: 83, name: "Professional, Scientific, and Technical Services" },
        { id: 84, name: "Publishing Industries (except Internet)" },
        { id: 85, name: "Rail Transportation" },
        { id: 86, name: "Real Estate" },
        { id: 87, name: "Real Estate and Rental and Leasing" },
        { id: 88, name: "Religious, Grantmaking, Civic, Professional, and Similar Organizations" },
        { id: 89, name: "Rental and Leasing Services" },
        { id: 90, name: "Repair and Maintenance" },
        { id: 91, name: "Retail Trade" },
        { id: 92, name: "Scenic and Sightseeing Transportation" },
        { id: 93, name: "Securities, Commodity Contracts, and Other Financial Investments and Related Activities" },
        { id: 94, name: "Service-Providing Industries" },
        { id: 95, name: "Social Assistance" },
        { id: 96, name: "Specialty Trade Contractors" },
        { id: 97, name: "Sporting Goods, Hobby, Book, and Music Stores" },
        { id: 98, name: "Support Activities for Agriculture and Forestry" },
        { id: 99, name: "Support Activities for Mining" },
        { id: 100, name: "Support Activities for Transportation" },
        { id: 101, name: "Telecommunications" },
        { id: 102, name: "Textile Mills" },
        { id: 103, name: "Textile Product Mills" },
        { id: 104, name: "Trade, Transportation, and Utilities" },
        { id: 105, name: "Transit and Ground Passenger Transportation" },
        { id: 106, name: "Transportation Equipment Manufacturing" },
        { id: 107, name: "Transportation and Warehousing" },
        { id: 108, name: "Truck Transportation" },
        { id: 109, name: "Utilities" },
        { id: 110, name: "Warehousing and Storage" },
        { id: 111, name: "Waste Management and Remediation Services" },
        { id: 112, name: "Water Transportation" },
        { id: 113, name: "Wholesale Electronic Markets and Agents and Brokers" },
        { id: 114, name: "Wholesale Trade" },
        { id: 115, name: "Wood Product Manufacturing" },
        { id: 116, name: "Technology" }
      ];
      
      let funding_status=[
        {id:1,name:"Ready to fund"},
        {id:2,name:"Looking for funds"},
        {id:3,name:"Having funds"},
      ];

      let funding_source=[
        {id:1,name:"Bootstrapped"},
        {id:2,name:"Backed by Investor"},
      ];

      let company_data= [
        { id: 1, name: "Wal-Mart Stores" },
        { id: 2, name: "Exxon Mobil" },
        { id: 3, name: "Chevron" },
        { id: 4, name: "Berkshire Hathaway" },
        { id: 5, name: "Apple" },
        { id: 6, name: "Phillips 66" },
        { id: 7, name: "General Motors" },
        { id: 8, name: "Ford Motor" },
        { id: 9, name: "General Electric" },
        { id: 10, name: "Valero Energy" },
        { id: 11, name: "AT&T" },
        { id: 12, name: "CVS Caremark" },
        { id: 13, name: "Fannie Mae" },
        { id: 14, name: "UnitedHealth Group" },
        { id: 15, name: "McKesson" },
        { id: 16, name: "Verizon Communications" },
        { id: 17, name: "Hewlett-Packard" },
        { id: 18, name: "J.P. Morgan Chase & Co." },
        { id: 19, name: "Costco Wholesale" },
        { id: 20, name: "Express Scripts Holding" },
        { id: 21, name: "Bank of America" },
        { id: 22, name: "Cardinal Health" },
        { id: 23, name: "International Business Machines" },
        { id: 24, name: "Kroger" },
        { id: 25, name: "Marathon Petroleum" },
        { id: 26, name: "Citigroup" },
        { id: 27, name: "Archer Daniels Midland" },
        { id: 28, name: "AmerisourceBergen" },
        { id: 29, name: "Wells Fargo" },
        { id: 30, name: "Boeing" },
        { id: 31, name: "Procter & Gamble" },
        { id: 32, name: "Freddie Mac" },
        { id: 33, name: "Home Depot" },
        { id: 34, name: "Microsoft" },
        { id: 35, name: "Amazon.com" },
        { id: 36, name: "Target" },
        { id: 37, name: "Walgreen Co." },
        { id: 38, name: "WellPoint" },
        { id: 39, name: "Johnson & Johnson" },
        { id: 40, name: "American International Group" },
        { id: 41, name: "State Farm Insurance Cos." },
        { id: 42, name: "MetLife" },
        { id: 43, name: "PepsiCo" },
        { id: 44, name: "Comcast" },
        { id: 45, name: "United Technologies" },
        { id: 46, name: "Google" },
        { id: 47, name: "ConocoPhillips" },
        { id: 48, name: "Dow Chemical" },
        { id: 49, name: "Caterpillar" },
        { id: 50, name: "United Parcel Service" },
        { id: 51, name: "Pfizer" },
        { id: 52, name: "Lowe’s Companies" },
        { id: 53, name: "Intel Corporation" },
        { id: 54, name: "Energy Transfer Equity, L.P." },
        { id: 55, name: "Cisco Systems, Inc." },
        { id: 56, name: "Enterprise Products Partners L.P." },
        { id: 57, name: "Aetna Inc." },
        { id: 58, name: "The Coca-Cola Company" },
        { id: 59, name: "Lockheed Martin Corporation" },
        { id: 60, name: "Best Buy Co., Inc." },
        { id: 61, name: "The Walt Disney Company" },
        { id: 62, name: "CHS Inc." },
        { id: 63, name: "Sysco Corporation" },
        { id: 64, name: "FedEx Corporation" },
        { id: 65, name: "Merck & Co., Inc." },
        { id: 66, name: "INTL FCStone Inc." },
        { id: 67, name: "Safeway Inc." },
        { id: 68, name: "Johnson Controls, Inc." },
        { id: 69, name: "Ingram Micro Inc." },
        { id: 70, name: "Plains GP Holdings, L.P." },
        { id: 71, name: "World Fuel Services Corporation" },
        { id: 72, name: "Prudential Financial, Inc." },
        { id: 73, name: "Humana Inc." },
        { id: 74, name: "The Goldman Sachs Group, Inc." },
        { id: 75, name: "Tesoro Corporation" },
        { id: 76, name: "Liberty Mutual Holding Company Inc." },
        { id: 77, name: "Honeywell International Inc." },
        { id: 78, name: "United Continental Holdings, Inc." },
        { id: 79, name: "HCA Holdings, Inc." },
        { id: 80, name: "Deere & Company" },
        { id: 81, name: "Delta Air Lines, Inc." },
        { id: 82, name: "Oracle Corporation" },
        { id: 83, name: "Morgan Stanley" },
        { id: 84, name: "Hess Corporation" },
        { id: 85, name: "Twenty-First Century Fox, Inc." },
        { id: 86, name: "E.I. du Pont de Nemours and Company" },
        { id: 87, name: "Sears Holdings Corporation" },
        { id: 88, name: "New York Life Insurance Company" },
        { id: 89, name: "Mondelez International, Inc." },
        { id: 90, name: "American Express Company" },
        { id: 91, name: "Nationwide Mutual Insurance Co." },
        { id: 92, name: "The Allstate Corporation" },
        { id: 93, name: "Tyson Foods, Inc." },
        { id: 94, name: "Supervalu Inc." },
        { id: 95, name: "TIAA-CREF" },
        { id: 96, name: "Massachusetts Mutual Life Insurance Company" },
        { id: 97, name: "CIGNA Corporation" },
        { id: 98, name: "DIRECTV" },
        { id: 99, name: "General Dynamics Corporation" },
        { id: 100, name: "Philip Morris International Inc." },
        { id: 101, name: "3M Company" },
        { id: 102, name: "Time Warner Inc." },
        { id: 103, name: "Halliburton Company" },
        { id: 104, name: "Publix Super Markets, Inc." },
        { id: 105, name: "International Paper Company" },
        { id: 106, name: "McDonald’s Corporation" },
        { id: 107, name: "Macy’s, Inc." },
        { id: 108, name: "The TJX Companies, Inc." },
        { id: 109, name: "Fluor Corporation" },
        { id: 110, name: "Northwestern Mutual Life Insurance Company, Inc." },
        { id: 111, name: "Tech Data Corporation" },
        { id: 112, name: "American Airlines Group Inc." },
        { id: 113, name: "The Hartford Financial Services Group, Inc." },
        { id: 114, name: "The Travelers Companies, Inc." },
        { id: 115, name: "Nike, Inc." },
        { id: 116, name: "Occidental Petroleum Corporation" },
        { id: 117, name: "Avnet, Inc." },
        { id: 118, name: "Rite Aid Corporation" },
        { id: 119, name: "Exelon Corporation" },
        { id: 120, name: "Qualcomm Incorporated" },
        { id: 121, name: "Emerson Electric Co." },
        { id: 122, name: "Northrop Grumman Corporation" },
        { id: 123, name: "Duke Energy Corporation" },
        { id: 124, name: "Capital One Financial Corporation" },
        { id: 125, name: "Aflac Incorporated" },
        { id: 126, name: "Raytheon Company" },
        { id: 127, name: "Staples, Inc." },
        { id: 128, name: "EMC Corporation" },
        { id: 129, name: "Eli Lilly and Company" },
        { id: 130, name: "Alcoa Inc." },
        { id: 131, name: "National Oilwell Varco, Inc." },
        { id: 132, name: "Baker Hughes Incorporated" },
        { id: 133, name: "US Foods, Inc." },
        { id: 134, name: "Time Warner Cable Inc." },
        { id: 135, name: "Union Pacific Corporation" },
        { id: 136, name: "Abbott Laboratories" },
        { id: 137, name: "Xerox Corporation" },
        { id: 138, name: "Arrow Electronics, Inc" },
        { id: 139, name: "Kimberly-Clark Corporation" },
        { id: 140, name: "U.S. Bancorp" },
        { id: 141, name: "United Services Automobile Association" },
        { id: 142, name: "Freeport-McMoRan Copper & Gold Inc." },
        { id: 143, name: "Icahn Enterprises L.P." },
        { id: 144, name: "ManpowerGroup Inc." },
        { id: 145, name: "HollyFrontier Corporation" },
        { id: 146, name: "Global Partners LP" },
        { id: 147, name: "The Goodyear Tire & Rubber Company" },
        { id: 148, name: "PBF Energy Inc." },
        { id: 149, name: "Danaher Corporation" },
        { id: 150, name: "Nucor Corporation" },
        { id: 151, name: "Kohl’s Corporation" },
        { id: 152, name: "AbbVie Inc." },
        { id: 153, name: "Whirlpool Corporation" },
        { id: 154, name: "Amgen Inc." },
        { id: 155, name: "Jabil Circuit, Inc." },
        { id: 156, name: "Kraft Foods Group, Inc." },
        { id: 157, name: "The Progressive Corporation" },
        { id: 158, name: "CenturyLink, Inc." },
        { id: 159, name: "General Mills, Inc." },
        { id: 160, name: "Southwest Airlines Co." },
        { id: 161, name: "Altria Group, Inc." },
        { id: 162, name: "AutoNation, Inc." },
        { id: 163, name: "Chesapeake Energy Corporation" },
        { id: 164, name: "Dollar General Corporation" },
        { id: 165, name: "TRW Automotive Holdings Corp." },
        { id: 166, name: "United States Steel Corporation" },
        { id: 167, name: "Colgate-Palmolive Company" },
        { id: 168, name: "Cummins Inc." },
        { id: 169, name: "PACCAR Inc" },
        { id: 170, name: "The Southern Company" },
        { id: 171, name: "Illinois Tool Works Inc." },
        { id: 172, name: "The PNC Financial Services Group, Inc." },
        { id: 173, name: "Medtronic, Inc." },
        { id: 174, name: "The AES Corporation" },
        { id: 175, name: "Murphy USA Inc." },
        { id: 176, name: "Bristol-Myers Squibb Company" },
        { id: 177, name: "Lear Corporation" },
        { id: 178, name: "The Gap, Inc." },
        { id: 179, name: "Apache Corporation" },
        { id: 180, name: "eBay Inc." },
        { id: 181, name: "The Bank of New York Mellon Corporation" },
        { id: 182, name: "CBS Corporation" },
        { id: 183, name: "PG&E Corporation" },
        { id: 184, name: "ConAgra Foods, Inc." },
        { id: 185, name: "Computer Sciences Corporation" },
        { id: 186, name: "American Electric Power Company, Inc." },
        { id: 187, name: "Western Digital Corporation" },
        { id: 188, name: "Marathon Oil Corporation" },
        { id: 189, name: "Baxter International Inc." },
        { id: 190, name: "PPG Industries, Inc." },
        { id: 191, name: "NextEra Energy, Inc." },
        { id: 192, name: "Community Health Systems, Inc." },
        { id: 193, name: "Loews Corporation" },
        { id: 194, name: "Penske Automotive Group, Inc." },
        { id: 195, name: "FirstEnergy Corp." },
        { id: 196, name: "Starbucks Corporation" },
        { id: 197, name: "Monsanto Company" },
        { id: 198, name: "Kellogg Company" },
        { id: 199, name: "Land O’Lakes, Inc." },
        { id: 200, name: "ONEOK, Inc." },
        { id: 201, name: "Omnicom Group Inc." },
        { id: 202, name: "Anadarko Petroleum Corporation" },
        { id: 203, name: "EOG Resources, Inc." },
        { id: 204, name: "DISH Network Corporation" },
        { id: 205, name: "Genuine Parts Company" },
        { id: 206, name: "Kinder Morgan, Inc." },
        { id: 207, name: "Waste Management, Inc." },
        { id: 208, name: "The Chubb Corporation" },
        { id: 209, name: "Aramark Holdings Corporation" },
        { id: 210, name: "Viacom Inc." },
        { id: 211, name: "Las Vegas Sands Corp." },
        { id: 212, name: "Dominion Resources, Inc." },
        { id: 213, name: "Ecolab Inc." },
        { id: 214, name: "Smithfield Foods, Inc." },
        { id: 215, name: "Thermo Fisher Scientific Inc." },
        { id: 216, name: "Yum! Brands, Inc." },
        { id: 217, name: "Parker-Hannifin Corporation" },
        { id: 218, name: "Whole Foods Market, Inc." },
        { id: 219, name: "Marriott International, Inc." },
        { id: 220, name: "C. H. Robinson Worldwide, Inc." },
        { id: 221, name: "L-3 Communications Holdings, Inc." },
        { id: 222, name: "Edison International" },
        { id: 223, name: "Toys “R” Us, Inc." },
        { id: 224, name: "Nordstrom, Inc." },
        { id: 225, name: "Consolidated Edison, Inc." },
        { id: 226, name: "Marsh & McLennan Companies, Inc." },
        { id: 227, name: "Texas Instruments Incorporated" },
        { id: 228, name: "Textron Inc." },
        { id: 229, name: "Tenet Healthcare Corporation" },
        { id: 230, name: "DaVita HealthCare Partners Inc." },
        { id: 231, name: "CSX Corporation" },
        { id: 232, name: "Lincoln National Corporation" },
        { id: 233, name: "Praxair, Inc." },
        { id: 234, name: "PPL Corporation" },
        { id: 235, name: "J.C. Penney Company, Inc." },
        { id: 236, name: "Peter Kiewit Sons’, Inc." },
        { id: 237, name: "Jacobs Engineering Group Inc." },
        { id: 238, name: "Visa Inc." },
        { id: 239, name: "H.J. Heinz Company" },
        { id: 240, name: "CarMax, Inc." },
        { id: 241, name: "V.F. Corporation" },
        { id: 242, name: "Entergy Corporation" },
        { id: 243, name: "Automatic Data Processing, Inc." },
        { id: 244, name: "NRG Energy, Inc." },
        { id: 245, name: "Guardian Life Ins. Co. of America" },
        { id: 246, name: "Liberty Interactive Corporation" },
        { id: 247, name: "Norfolk Southern Corporation" },
        { id: 248, name: "Office Depot, Inc." },
        { id: 249, name: "Ameriprise Financial, Inc." },
        { id: 250, name: "Gilead Sciences, Inc." },
        { id: 251, name: "Centene Corporation" },
        { id: 252, name: "Leucadia National Corporation" },
        { id: 253, name: "Huntsman Corporation" },
        { id: 254, name: "Health Net, Inc." },
        { id: 255, name: "Stanley Black & Decker, Inc." },
        { id: 256, name: "URS Corporation" },
        { id: 257, name: "Xcel Energy Inc." },
        { id: 258, name: "Bed Bath & Beyond Inc." },
        { id: 259, name: "Navistar International Corporation" },
        { id: 260, name: "Synnex Corporation" },
        { id: 261, name: "First Data Corporation" },
        { id: 262, name: "AGCO Corporation" },
        { id: 263, name: "L Brands, Inc." },
        { id: 264, name: "Hertz Global Holdings, Inc." },
        { id: 265, name: "CDW Corporation" },
        { id: 266, name: "CST Brands, Inc." },
        { id: 267, name: "Sempra Energy" },
        { id: 268, name: "R.R. Donnelley & Sons Company" },
        { id: 269, name: "BB&T Corporation" },
        { id: 270, name: "Devon Energy Corporation" },
        { id: 271, name: "Family Dollar Stores, Inc." },
        { id: 272, name: "Unum Group" },
        { id: 273, name: "Ally Financial Inc." },
        { id: 274, name: "Reinsurance Group of America, Incorporated" },
        { id: 275, name: "State Street Corporation" },
        { id: 276, name: "Air Products & Chemicals, Inc." },
        { id: 277, name: "Ross Stores, Inc." },
        { id: 278, name: "The Sherwin-Williams Company" },
        { id: 279, name: "The Estée Lauder Companies Inc." },
        { id: 280, name: "BlackRock, Inc." },
        { id: 281, name: "Western Refining, Inc." },
        { id: 282, name: "Owens-Illinois, Inc." },
        { id: 283, name: "The Mosaic Company" },
        { id: 284, name: "Discovery Communications, Inc." },
        { id: 285, name: "Harris Corporation" },
        { id: 286, name: "Graybar Electric Company, Inc." },
        { id: 287, name: "Kelley Drye & Warren LLP" },
        { id: 288, name: "Molina Healthcare, Inc." },
        { id: 289, name: "Terex Corporation" },
        { id: 290, name: "The Boston Consulting Group, Inc." },
        { id: 291, name: "The Blackstone Group L.P." },
        { id: 292, name: "Jacobs Entertainment Inc." },
        { id: 293, name: "NuStar Energy L.P." },
        { id: 294, name: "Chubb Limited" },
        { id: 295, name: "WESCO International, Inc." },
        { id: 296, name: "Arthur J. Gallagher & Co." },
        { id: 297, name: "Owens Corning" },
        { id: 298, name: "Franklin Resources, Inc." },
        { id: 299, name: "Airgas, Inc." },
        { id: 300, name: "CH2M HILL Companies, Ltd." },
        { id: 301, name: "Rock-Tenn Company" },
        { id: 302, name: "The Reynolds and Reynolds Company" },
        { id: 303, name: "NiSource Inc." },
        { id: 304, name: "ManTech International Corporation" },
        { id: 305, name: "Legg Mason, Inc." },
        { id: 306, name: "KBR, Inc." },
        { id: 307, name: "SanDisk Corporation" },
        { id: 308, name: "Commercial Metals Company" },
        { id: 309, name: "Avery Dennison Corporation" },
        { id: 310, name: "Comerica Incorporated" },
        { id: 311, name: "SCANA Corporation" },
        { id: 312, name: "Rockwell Automation, Inc." },
        { id: 313, name: "Guardian Industries Corp." },
        { id: 314, name: "Energen Corporation" },
        { id: 315, name: "Nielsen Holdings plc" },
        { id: 316, name: "TE Connectivity Ltd." },
        { id: 317, name: "EOG Resources, Inc." },
        { id: 318, name: "Western Digital Corporation" },
        { id: 319, name: "Marathon Oil Corporation" },
        { id: 320, name: "Baxter International Inc." },
        { id: 321, name: "PPG Industries, Inc." },
        { id: 322, name: "NextEra Energy, Inc." },
        { id: 323, name: "Community Health Systems, Inc." },
        { id: 324, name: "Loews Corporation" },
        { id: 325, name: "Penske Automotive Group, Inc." },
        { id: 326, name: "FirstEnergy Corp." },
        { id: 327, name: "Starbucks Corporation" },
        { id: 328, name: "Monsanto Company" },
        { id: 329, name: "Kellogg Company" },
        { id: 330, name: "Land O’Lakes, Inc." }
      ];

      return {
        user_data_val:user_data,
        domain_data_val:domain_data,
        funding_status_val:funding_status,
        funding_source_val:funding_source,
        company_data_val:company_data
      }


})();

export default ProfileData;



